import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from './components/Sidebar'
<<<<<<< HEAD
import Signup from './signup/page'
=======
import Details from './details/page'
import DataUpload from './datamanagement/page'
>>>>>>> 4f75a6ff76d99496b3c961bfd2419401a9a45b90


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex'>
<<<<<<< HEAD
          {/* <Signup/> */}
          {children} 
=======
          
          {/* {children} */}
      <Details/>
          
       
     

         
>>>>>>> 4f75a6ff76d99496b3c961bfd2419401a9a45b90
        </div>
      </body>
    </html>
  )
}
