name: Next.js CI/CD
on:
  push:
    branches:
      main
      dev
      staging
  pull_request:
    branches:
      main
      dev
      staging
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 
    - name: Install Packages
      run: npm install
    - name: Check Formatting
      run: npm run build
    - name: Build
      run: npm run build

